version: '3.8'

services:
  kafka-broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_CLUSTER_ID: kafka-cluster-1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    command: >
      sh -c "/opt/kafka/bin/kafka-storage.sh format --ignore-formatted --cluster-id kafka-cluster-1 --config /opt/kafka/config/kraft/server.properties &&
             /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties & 
             sleep 10 &&
             /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic order-items-topic --partitions 1 --replication-factor 1 &&
             tail -f /dev/null"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  some-postgres:
    image: postgres:latest
    container_name: some-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
